### ISSUE TITLE
I follow the set up step by step but its not working

### ISSUE THREAD

**Issue by exeoscar** [api-ai/apiai-webhook-sample#10]
Please find in my screen cap

Setup Instructions

Option #1: Dialogflow Inline Editor (recommended)

Enable the Cloud Function for Firebase inline editor
Copy this code in functions/index.js the index.js file in the Dialogflow Cloud Function for Firebase inline editor.
Copy this code in functions/package.json the package.json file in the Dialogflow Cloud Function for Firebase inline editor.
Click Deploy

<img width="801" alt="2018-07-03 11 01 26" src="https://user-images.githubusercontent.com/40800229/42227893-2f64cd3e-7f15-11e8-9417-340fd18ecbd4.png">
<img width="807" alt="2018-07-03 11 01 34" src="https://user-images.githubusercontent.com/40800229/42227895-2f99e758-7f15-11e8-8048-5c81619b7ce4.png">
<img width="774" alt="2018-07-03 11 01 42" src="https://user-images.githubusercontent.com/40800229/42227896-2fe4fe3c-7f15-11e8-9f08-085b80941c73.png">

**Comment by findzaatar** [comment]
@exeoscar You'll need to copy the contents of index.js and package.json from this repo and paste them into the Dialogflow Console's Inline Editor in order to deploy.
