### ISSUE TITLE
What's the structure needed in dialogflow webhook V2 response to return either List or Carousel?

### ISSUE THREAD

**Issue by maximedotair** [api-ai/apiai-webhook-sample#9]
I have seen most of the examples related to how to return rich content via webhooks involving just basic response and Card.

https://github.com/dialogflow/fulfillment-webhook-nodejs/blob/master/functions/index.js

What's the structure needed in dialogflow webhook V2 response to return either List or Carousel?

**Comment by findzaatar** [comment]
@kwizfreak You should check out: https://developers.google.com/actions/assistant/responses#list and https://developers.google.com/actions/assistant/responses#carousel
